/*
 * This source file was generated by the Gradle 'init' task
 */
package com.crio.qcalc;

// class to test functionality
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("Starting QCalc..");
        // StandardCalculator calc = new StandardCalculator();
        // calc.subtract(-Double.MAX_VALUE, Double.MAX_VALUE);
        LogicCalculator calc = new LogicCalculator();
        calc.AND(8, 6);
        calc.printResult();
        calc.OR(8, 6);
        calc.printResult();
        calc.XOR(8, 6);
        calc.printResult();
        calc.NOT(8);
        calc.printResult();
        
    }
}
